// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-gn1m4b04dEm67LpeE3k_YmqDbn1f9YE',
    appId: '1:131749883739:web:59929403cf04937cab347e',
    messagingSenderId: '131749883739',
    projectId: 'shayak-setu',
    authDomain: 'shayak-setu.firebaseapp.com',
    storageBucket: 'shayak-setu.firebasestorage.app',
    measurementId: 'G-7GVMT7SHX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyMyCWEVHgrkP5GEyCXBkF2EmekZln4A',
    appId: '1:131749883739:android:70374bb2d1ac9804ab347e',
    messagingSenderId: '131749883739',
    projectId: 'shayak-setu',
    storageBucket: 'shayak-setu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCynboNe8jrDC6nxnfHhmkFRg6XTHMCqYs',
    appId: '1:131749883739:ios:ea5c73857ddb24e2ab347e',
    messagingSenderId: '131749883739',
    projectId: 'shayak-setu',
    storageBucket: 'shayak-setu.firebasestorage.app',
    iosBundleId: 'com.example.sahayakSetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCynboNe8jrDC6nxnfHhmkFRg6XTHMCqYs',
    appId: '1:131749883739:ios:ea5c73857ddb24e2ab347e',
    messagingSenderId: '131749883739',
    projectId: 'shayak-setu',
    storageBucket: 'shayak-setu.firebasestorage.app',
    iosBundleId: 'com.example.sahayakSetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-gn1m4b04dEm67LpeE3k_YmqDbn1f9YE',
    appId: '1:131749883739:web:80ee754ad8796edeab347e',
    messagingSenderId: '131749883739',
    projectId: 'shayak-setu',
    authDomain: 'shayak-setu.firebaseapp.com',
    storageBucket: 'shayak-setu.firebasestorage.app',
    measurementId: 'G-7RSJV5J55K',
  );
}
